[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/translate"
  to = "/.netlify/functions/translate"
  status = 200

[[redirects]]
  from = "/api/hub-get"
  to = "/.netlify/functions/hub-get"
  status = 200

[[redirects]]
  from = "/hub-get"
  to = "/.netlify/functions/hub-get"
  status = 200

[[redirects]]
  from = "/api/hub-add"
  to = "/.netlify/functions/hub-add"
  status = 200

[[redirects]]
  from = "/hub-add"
  to = "/.netlify/functions/hub-add"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
